### ISSUE TITLE
Errors installing from arduino ide and .zip

### ISSUE THREAD

**Issue by g7kse** [ropg/M5ez#127]
Afternoon,

I have attempted to install the library by the arduino ide and via a zip without any success. library shows as white text instead of orange that indicates to me that it isn't installed correctly / is missing something. Output from installation is

`no protocol: 
java.lang.RuntimeException: java.net.MalformedURLException: no protocol: 
	at cc.arduino.contributions.libraries.ui.LibraryManagerUI.lambda$onInstallPressed$4(LibraryManagerUI.java:250)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.MalformedURLException: no protocol: 
	at java.base/java.net.URL.<init>(URL.java:645)
	at java.base/java.net.URL.<init>(URL.java:541)
	at java.base/java.net.URL.<init>(URL.java:488)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:64)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:60)
	at cc.arduino.contributions.libraries.LibraryInstaller.performInstall(LibraryInstaller.java:155)
	at cc.arduino.contributions.libraries.LibraryInstaller.install(LibraryInstaller.java:125)
	at cc.arduino.contributions.libraries.ui.LibraryManagerUI.lambda$onInstallPressed$4(LibraryManagerUI.java:240)
	... 1 more
`

looks as thoughit is similar to #102 hello world compile error is...

`/home/alex/snap/arduino/current/Arduino/libraries/M5ez/src/M5ez.cpp: In lambda function:
/home/alex/snap/arduino/current/Arduino/libraries/M5ez/src/M5ez.cpp:1133:38: error: 'union arduino_event_info_t' has no member named 'disconnected'; did you mean 'eth_connected'?
    if(WIFI_REASON_ASSOC_FAIL == info.disconnected.reason) {
                                      ^~~~~~~~~~~~
                                      eth_connected
/home/alex/snap/arduino/current/Arduino/libraries/M5ez/src/M5ez.cpp: In static member function 'static void ezWifi::begin()':
/home/alex/snap/arduino/current/Arduino/libraries/M5ez/src/M5ez.cpp:1139:19: error: 'SYSTEM_EVENT_STA_DISCONNECTED' is not a member of 'arduino_event_id_t'
   }, WiFiEvent_t::SYSTEM_EVENT_STA_DISCONNECTED);
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/alex/snap/arduino/current/Arduino/libraries/M5ez/src/M5ez.cpp: In static member function 'static bool ezWifi::_connection(ezMenu*)':
/home/alex/snap/arduino/current/Arduino/libraries/M5ez/src/M5ez.cpp:1410:13: error: 'struct esp_wps_config_t' has no member named 'crypto_funcs'
      config.crypto_funcs = &g_wifi_default_wps_crypto_funcs;
             ^~~~~~~~~~~~
/home/alex/snap/arduino/current/Arduino/libraries/M5ez/src/M5ez.cpp:1410:29: error: 'g_wifi_default_wps_crypto_funcs' was not declared in this scope
      config.crypto_funcs = &g_wifi_default_wps_crypto_funcs;
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/alex/snap/arduino/current/Arduino/libraries/M5ez/src/M5ez.cpp:1410:29: note: suggested alternative: 'g_wifi_default_wpa_crypto_funcs'
      config.crypto_funcs = &g_wifi_default_wps_crypto_funcs;
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                             g_wifi_default_wpa_crypto_funcs
/home/alex/snap/arduino/current/Arduino/libraries/M5ez/src/M5ez.cpp:1420:29: error: no matching function for call to 'onEvent(void (&)(arduino_event_id_t, system_event_info_t))'
      WiFi.onEvent(_WPShelper);
                             ^
In file included from /home/alex/snap/arduino/61/.arduino15/packages/esp32/hardware/esp32/2.0.0/libraries/WiFi/src/WiFiSTA.h:28,
                 from /home/alex/snap/arduino/61/.arduino15/packages/esp32/hardware/esp32/2.0.0/libraries/WiFi/src/WiFi.h:32,
                 from /home/alex/snap/arduino/current/Arduino/libraries/M5ez/src/M5ez.h:36,
                 from /home/alex/snap/arduino/current/Arduino/libraries/M5ez/src/M5ez.cpp:1:
/home/alex/snap/arduino/61/.arduino15/packages/esp32/hardware/esp32/2.0.0/libraries/WiFi/src/WiFiGeneric.h:147:21: note: candidate: 'wifi_event_id_t WiFiGenericClass::onEvent(WiFiEventCb, arduino_event_id_t)' <near match>
     wifi_event_id_t onEvent(WiFiEventCb cbEvent, arduino_event_id_t event = ARDUINO_EVENT_MAX);
                     ^~~~~~~
/home/alex/snap/arduino/61/.arduino15/packages/esp32/hardware/esp32/2.0.0/libraries/WiFi/src/WiFiGeneric.h:147:21: note:   conversion of argument 1 would be ill-formed:
/home/alex/snap/arduino/current/Arduino/libraries/M5ez/src/M5ez.cpp:1420:29: error: invalid conversion from 'void (*)(arduino_event_id_t, system_event_info_t)' to 'WiFiEventCb' {aka 'void (*)(arduino_event_id_t)'} [-fpermissive]
      WiFi.onEvent(_WPShelper);
                             ^
In file included from /home/alex/snap/arduino/61/.arduino15/packages/esp32/hardware/esp32/2.0.0/libraries/WiFi/src/WiFiSTA.h:28,
                 from /home/alex/snap/arduino/61/.arduino15/packages/esp32/hardware/esp32/2.0.0/libraries/WiFi/src/WiFi.h:32,
                 from /home/alex/snap/arduino/current/Arduino/libraries/M5ez/src/M5ez.h:36,
                 from /home/alex/snap/arduino/current/Arduino/libraries/M5ez/src/M5ez.cpp:1:
/home/alex/snap/arduino/61/.arduino15/packages/esp32/hardware/esp32/2.0.0/libraries/WiFi/src/WiFiGeneric.h:149:21: note: candidate: 'wifi_event_id_t WiFiGenericClass::onEvent(WiFiEventSysCb, arduino_event_id_t)' <near match>
     wifi_event_id_t onEvent(WiFiEventSysCb cbEvent, arduino_event_id_t event = ARDUINO_EVENT_MAX);
                     ^~~~~~~
/home/alex/snap/arduino/61/.arduino15/packages/esp32/hardware/esp32/2.0.0/libraries/WiFi/src/WiFiGeneric.h:149:21: note:   conversion of argument 1 would be ill-formed:
/home/alex/snap/arduino/current/Arduino/libraries/M5ez/src/M5ez.cpp:1420:29: error: invalid conversion from 'void (*)(arduino_event_id_t, system_event_info_t)' to 'WiFiEventSysCb' {aka 'void (*)(arduino_event_t*)'} [-fpermissive]
      WiFi.onEvent(_WPShelper);
                             ^
/home/alex/snap/arduino/current/Arduino/libraries/M5ez/src/M5ez.cpp: In static member function 'static void ezWifi::_WPShelper(arduino_event_id_t, system_event_info_t)':
/home/alex/snap/arduino/current/Arduino/libraries/M5ez/src/M5ez.cpp:1467:17: warning: comparison between 'enum arduino_event_id_t' and 'enum system_event_id_t' [-Wenum-compare]
    if (event == SYSTEM_EVENT_STA_WPS_ER_PIN) {
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/alex/snap/arduino/current/Arduino/libraries/M5ez/src/M5ez.cpp: At global scope:
/home/alex/snap/arduino/current/Arduino/libraries/M5ez/src/M5ez.cpp:2238:2: warning: unknown escape sequence: '\|'
  "KB14|!?:;\\#$^&#SP#KB15|*()_-+=\|#Del#KB0|More#LCK:SYM|Lock#KB16|'\"`@%\\/#KB17|<>{}[]()#Done", //KB13
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/alex/snap/arduino/current/Arduino/libraries/M5ez/src/M5ez.cpp:2241:2: warning: unknown escape sequence: '\#'
  "'#\"#`#@#%#/#\##Back",                //KB16
  ^~~~~~~~~~~~~~~~~~~~~~
Multiple libraries were found for "WiFi.h"
 Used: /home/alex/snap/arduino/61/.arduino15/packages/esp32/hardware/esp32/2.0.0/libraries/WiFi
 Not used: /snap/arduino/61/libraries/WiFi
Multiple libraries were found for "SD.h"
 Used: /home/alex/snap/arduino/61/.arduino15/packages/esp32/hardware/esp32/2.0.0/libraries/SD
 Not used: /snap/arduino/61/libraries/SD
exit status 1
Error compiling for board M5Stack-Core-ESP32.`

**Comment by mrdunk** [comment]
I just ran into this too.
Looks like M5Stack have move on to a more recent version of the networking API.

I have found 2 possible workarounds:

1. Pin "M5Stack" to version 1.0.9 in Arduino's "Boards Manager" to match what M5ez is expecting.
2. In the source file `~/Arduino/libraries/M5ez/src/M5ez.cpp` modify the `ezWifi::begin()` function:
```
	void ezWifi::begin() {
		#ifdef M5EZ_WIFI_DEBUG
			Serial.println("EZWIFI: Initialising");
		#endif
		WiFi.mode(WIFI_MODE_STA);
		WiFi.setAutoConnect(false);		// We have our own multi-AP version of this
		WiFi.setAutoReconnect(false);	// So we turn off the ESP32's versions
		WiFi.setHostname("M5Stack");
		ez.wifi.readFlash();
		_state = EZWIFI_IDLE;
		const uint8_t cutoffs[] = { 0, 20, 40, 70 };
		ez.settings.menuObj.addItem("Wifi settings", ez.wifi.menu);
		ez.header.insert(RIGHTMOST, "wifi", sizeof(cutoffs) * (ez.theme->signal_bar_width + ez.theme->signal_bar_gap) + 2 * ez.theme->header_hmargin, ez.wifi._drawWidget);
		// For handling issue #50, when initial connection attempt fails in this specific mode but will succeed if tried again.
		WiFi.onEvent([](WiFiEvent_t event, WiFiEventInfo_t info){
			if(WIFI_REASON_ASSOC_FAIL == info.wifi_sta_disconnected.reason) {     // <<<<< This line changed
			#ifdef M5EZ_WIFI_DEBUG
				Serial.println("EZWIFI: Special case: Disconnect w/ ASSOC_FAIL. Setting _state to EZWIFI_SCANNING;");
			#endif
			_state = EZWIFI_SCANNING;
		}
		}, WiFiEvent_t::ARDUINO_EVENT_WIFI_STA_DISCONNECTED);                 // <<<<< This line changed
		ez.addEvent(ez.wifi.loop);
	}
```
And i couldn't get WPS to work so in `~/Arduino/libraries/M5ez/src/M5ez.h`,
comment out the section:
```
//#define M5EZ_WPS
```

**Comment by LennartHennigs** [comment]
This worked for me:
https://community.m5stack.com/topic/4578/cant-compile-m5ez-h/8
